### ISSUE TITLE
Running on Mac OS X tests panic

### ISSUE THREAD

**Issue by dunnock** [jebrosen/async-file-benchmark#2]
Running on OSX 10.15.1, initially tests were failing:
```
thread 'main' panicked at 'failed to time: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

after creating file.dat via `touch file.dat` tests failing complaining on too manu open files. I had to change system parameters to fix that:

```
ulimit -S -n 10000
```

**Comment by jebrosen** [comment]
Yeah, I should explain proper setup in a README (`touch file.dat` won't really do anything since it's empty). I didn't really expect anyone to discover this so I didn't prioritize that. I'm fairly sure it doesn't benchmark what anyone thinks it does, probably including myself.

**Comment by jebrosen** [comment]
I've added setup instructions and a notice in the README.
